cabal-version: 3.6
name:          cabal-install-internal
version:       3.19.0.0
synopsis:      The internal implementation of cabal-install
description:
  The internal implementation modules of the cabal-install command-line
  program. This package is NOT a stable API: modules may be added, changed
  or removed in any release without notice. Third-party tools should depend
  on the public API exposed by the @cabal-install@ package instead.

homepage:      http://www.haskell.org/cabal/
bug-reports:   https://github.com/haskell/cabal/issues
license:       BSD-3-Clause
license-file:  LICENSE
author:        Cabal Development Team (see AUTHORS file)
maintainer:    Cabal Development Team <cabal-devel@haskell.org>
copyright:     2003-2026, Cabal Development Team
category:      Distribution
build-type:    Simple
extra-doc-files:
  ChangeLog.md

source-repository head
  type:     git
  location: https://github.com/haskell/cabal/
  subdir:   cabal-install-internal

flag native-dns
  description:
    Enable use of the [resolv](https://hackage.haskell.org/package/resolv)
    & [windns](https://hackage.haskell.org/package/windns) packages for performing DNS lookups
  default:      True
  manual:       True

flag git-rev
  description: include Git revision hash in version
  default: False
  manual: True

flag legacy-comparison
  description: Enable comparison between the new and legacy cabal.project parser
  default: False
  manual: True

library
    default-language: GHC2021
    -- Disabling ImportQualifiedPost, otherwise fourmolu jumps ahead to apply it everywhere
    default-extensions: TypeOperators
                        NoImportQualifiedPost
    hs-source-dirs:   src
    ghc-options:
      -Wall
      -Wcompat
      -Wnoncanonical-monad-instances
      -Wincomplete-uni-patterns
      -Wincomplete-record-updates
      -Wno-unticked-promoted-constructors

    if impl(ghc < 8.8)
      ghc-options: -Wnoncanonical-monadfail-instances

    if impl(ghc >= 9.14)
      ghc-options: -Wno-pattern-namespace-specifier -Wno-incomplete-record-selectors

    autogen-modules:
        Paths_cabal_install_internal
    other-modules:
        Paths_cabal_install_internal
    exposed-modules:
      Distribution.Client.BuildReports.Anonymous
      Distribution.Client.BuildReports.Lens
      Distribution.Client.BuildReports.Storage
      Distribution.Client.BuildReports.Types
      Distribution.Client.BuildReports.Upload
      Distribution.Client.Check
      Distribution.Client.CmdBench
      Distribution.Client.CmdBuild
      Distribution.Client.CmdClean
      Distribution.Client.CmdConfigure
      Distribution.Client.CmdErrorMessages
      Distribution.Client.CmdExec
      Distribution.Client.CmdFreeze
      Distribution.Client.CmdGenBounds
      Distribution.Client.CmdHaddock
      Distribution.Client.CmdHaddockProject
      Distribution.Client.CmdInstall
      Distribution.Client.CmdInstall.ClientInstallFlags
      Distribution.Client.CmdInstall.ClientInstallTargetSelector
      Distribution.Client.CmdLegacy
      Distribution.Client.CmdListBin
      Distribution.Client.CmdOutdated
      Distribution.Client.CmdPath
      Distribution.Client.CmdRepl
      Distribution.Client.CmdRun
      Distribution.Client.CmdSdist
      Distribution.Client.CmdTarget
      Distribution.Client.CmdTest
      Distribution.Client.CmdUpdate
      Distribution.Client.Compat.Orphans
      Distribution.Client.Compat.Prelude
      Distribution.Client.Compat.Semaphore
      Distribution.Client.Compat.Tar
      Distribution.Client.Config
      Distribution.Client.Configure
      Distribution.Client.Dependency
      Distribution.Client.Dependency.Types
      Distribution.Client.DistDirLayout
      Distribution.Client.Errors
      Distribution.Client.Errors.Parser
      Distribution.Client.Fetch
      Distribution.Client.FetchUtils
      Distribution.Client.FileMonitor
      Distribution.Client.Freeze
      Distribution.Client.GZipUtils
      Distribution.Client.GenBounds
      Distribution.Client.Get
      Distribution.Client.Glob
      Distribution.Client.GlobalFlags
      Distribution.Client.Haddock
      Distribution.Client.HashValue
      Distribution.Client.HttpUtils
      Distribution.Client.InLibrary
      Distribution.Client.IndexUtils
      Distribution.Client.IndexUtils.ActiveRepos
      Distribution.Client.IndexUtils.IndexState
      Distribution.Client.IndexUtils.Timestamp
      Distribution.Client.Init
      Distribution.Client.Init.Defaults
      Distribution.Client.Init.FileCreators
      Distribution.Client.Init.FlagExtractors
      Distribution.Client.Init.Format
      Distribution.Client.Init.Interactive.Command
      Distribution.Client.Init.Licenses
      Distribution.Client.Init.NonInteractive.Command
      Distribution.Client.Init.NonInteractive.Heuristics
      Distribution.Client.Init.Prompt
      Distribution.Client.Init.Simple
      Distribution.Client.Init.Types
      Distribution.Client.Init.Utils
      Distribution.Client.Install
      Distribution.Client.InstallPlan
      Distribution.Client.InstallSymlink
      Distribution.Client.JobControl
      Distribution.Client.List
      Distribution.Client.Main
      Distribution.Client.Manpage
      Distribution.Client.ManpageFlags
      Distribution.Client.NixStyleOptions
      Distribution.Client.PackageHash
      Distribution.Client.ParseUtils
      Distribution.Client.ProjectBuilding
      Distribution.Client.ProjectBuilding.PackageFileMonitor
      Distribution.Client.ProjectBuilding.Types
      Distribution.Client.ProjectBuilding.UnpackedPackage
      Distribution.Client.ProjectConfig
      Distribution.Client.ProjectConfig.FieldGrammar
      Distribution.Client.ProjectConfig.Import
      Distribution.Client.ProjectConfig.Legacy
      Distribution.Client.ProjectConfig.Lens
      Distribution.Client.ProjectConfig.Parsec
      Distribution.Client.ProjectConfig.Types
      Distribution.Client.ProjectFlags
      Distribution.Client.ProjectOrchestration
      Distribution.Client.ProjectPlanOutput
      Distribution.Client.ProjectPlanning
      Distribution.Client.ProjectPlanning.SetupPolicy
      Distribution.Client.ProjectPlanning.Types
      Distribution.Client.RebuildMonad
      Distribution.Client.Reconfigure
      Distribution.Client.ReplFlags
      Distribution.Client.Run
      Distribution.Client.Sandbox
      Distribution.Client.Sandbox.PackageEnvironment
      Distribution.Client.SavedFlags
      Distribution.Client.ScriptUtils
      Distribution.Client.Security.DNS
      Distribution.Client.Security.HTTP
      Distribution.Client.Setup
      Distribution.Client.SetupWrapper
      Distribution.Client.Signal
      Distribution.Client.SolverInstallPlan
      Distribution.Client.SourceFiles
      Distribution.Client.SrcDist
      Distribution.Client.Store
      Distribution.Client.Tar
      Distribution.Client.TargetProblem
      Distribution.Client.TargetSelector
      Distribution.Client.Targets
      Distribution.Client.Types
      Distribution.Client.Types.AllowNewer
      Distribution.Client.Types.BuildResults
      Distribution.Client.Types.ConfiguredId
      Distribution.Client.Types.ConfiguredPackage
      Distribution.Client.Types.Credentials
      Distribution.Client.Types.InstallMethod
      Distribution.Client.Types.OverwritePolicy
      Distribution.Client.Types.PackageLocation
      Distribution.Client.Types.PackageSpecifier
      Distribution.Client.Types.ReadyPackage
      Distribution.Client.Types.Repo
      Distribution.Client.Types.RepoName
      Distribution.Client.Types.SourcePackageDb
      Distribution.Client.Types.SourceRepo
      Distribution.Client.Types.WriteGhcEnvironmentFilesPolicy
      Distribution.Client.Upload
      Distribution.Client.Utils
      Distribution.Client.Utils.Json
      Distribution.Client.Utils.Newtypes
      Distribution.Client.Utils.Parsec
      Distribution.Client.VCS
      Distribution.Client.Version
      Distribution.Client.Win32SelfUpgrade
      Distribution.Deprecated.ParseUtils
      Distribution.Deprecated.ProjectParseUtils
      Distribution.Deprecated.ReadP
      Distribution.Deprecated.ViewAsFieldDescr

    build-depends:
        Cabal ^>=3.19
      , Cabal-syntax ^>=3.19
      , cabal-install-solver ^>=3.19
      , async      >= 2.0      && < 2.3
      , array      >= 0.4      && < 0.6
      , base16-bytestring >= 1.0 && < 1.1
      , binary     >= 0.7.3    && < 0.9
      , bytestring >= 0.10.6.0 && < 0.13
      , containers >= 0.5.6.2  && < 0.9
      , cryptohash-sha256 >= 0.11 && < 0.12
      , directory  >= 1.3.7.0  && < 1.4
      , echo       >= 0.1.3    && < 0.2
      , edit-distance >= 0.2.2 && < 0.3
      , exceptions >= 0.10.4   && < 0.11
      , filepath   >= 1.4.0.0  && < 1.6
      , hooks-exe ^>= 3.19
      , HTTP       >= 4000.1.5 && < 4000.6
      , mtl        >= 2.0      && < 2.4
      , network-uri >= 2.6.2.0 && < 2.7
      , pretty     >= 1.1      && < 1.2
      , process    >= 1.6.29.0 && < 1.7
      , random     >= 1.2      && < 1.4
      , stm        >= 2.0      && < 2.6
      , tar        >= 0.5.0.3  && < 0.8
      , time       >= 1.5.0.1  && < 1.17
      , zlib       >= 0.6      && < 0.8
      , hackage-security >= 0.6.2.0 && < 0.7
      , text       >= 1.2.3    && < 1.3 || >= 2.0 && < 2.2
      , parsec     >= 3.1.13.0 && < 3.2
      , open-browser >= 0.2.1.0 && < 0.6
      , regex-base  >= 0.94.0.0 && <0.95
      , regex-posix >= 0.96.0.0 && <0.97
      , safe-exceptions >= 0.1.7.0 && < 0.2
      , semaphore-compat >= 2.0.1 && < 2.1
      , base >=4.17 && <4.24

    if flag(native-dns)
      if os(windows)
        build-depends: windns      >= 0.1.0 && < 0.2
      else
        build-depends: resolv      >= 0.1.1 && < 0.3

    if os(windows)
      -- newer directory for symlinks
      build-depends:
        , Win32 >= 2.8 && < 3
        , directory >=1.3.1.0
    else
      build-depends:
        , unix >= 2.5 && < 2.8 || >= 2.8.6.0 && < 2.9

    if flag(git-rev)
      build-depends: githash ^>= 0.1.7.0
      cpp-options: -DGIT_REV

    if flag(legacy-comparison)
      cpp-options: -DLEGACY_COMPARISON
