module Main where

-- bt
import Tool
  ( mkTool )

-- pbts
import Paths_pbts -- (Cabal autogenerated module)
  ( getDataFileName )

--------------------------------------------------------------------------------

main :: IO ()
main = do
  customDataFile <- getDataFileName "PP2.txt"
  mkTool "custom-pp2" customDataFile
