resolver: lts-18.28 # ghc-8.10.7

packages:
- Cabal-syntax/
- Cabal/
- Cabal-hooks/
- Cabal-described
- Cabal-QuickCheck/
- Cabal-tests/
- Cabal-tree-diff/
- cabal-benchmarks/
- cabal-install-solver/
- cabal-install/
- cabal-testsuite/
- solver-benchmarks/

extra-deps:
# Not included in stackage
- rere-0.2@rev:1

# We require the released version of Cabal and Cabal-syntax for cabal-testsuite
# but usually we have a development, newer version set in the local package
# Also needed for hackage-security and Win32
allow-newer: true

nix:
  packages:
  - autoconf
  - automake
  - haskellPackages.happy
  - haskellPackages.alex
  - zlib
  - zlib.out
