resolver: lts-18.17

packages:
- Cabal-syntax/
- Cabal/
- Cabal-described
- Cabal-QuickCheck/
- Cabal-tests/
- Cabal-tree-diff/
- cabal-benchmarks/
- cabal-install-solver/
- cabal-install/
- cabal-testsuite/
- solver-benchmarks/

extra-deps:
- rere-0.2@sha256:ec1d87554c03755d89f3401c5e5c27827e61dde835c54cbdaf509136ce8f6f2b,4079

allow-newer: true

nix:
  packages:
  - autoconf
  - automake
  - haskellPackages.happy
  - haskellPackages.alex
  - zlib
  - zlib.out
