flags:
  text:
    integer-simple: false
packages:
- Cabal/
- cabal-install/
extra-deps:
- HTTP-4000.2.20
- mtl-2.2.1
- network-2.6.2.0
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.9
- random-1.1
- stm-2.4.4
- text-1.2.1.1
- zlib-0.5.4.2
resolver: ghc-7.10
