/* DO NOT EDIT: This file is automatically generated by Cabal */

{% for pkg in packages %}
/* package {{ pkg.name }}-{{ pkg.version }} */
#ifndef VERSION_{{ manglePkgName pkg.name }}
#define VERSION_{{ manglePkgName pkg.name }} "{{ pkg.version }}"
#endif /* VERSION_{{ manglePkgName pkg.name }} */
#ifndef MIN_VERSION_{{ manglePkgName pkg.name }}
#define MIN_VERSION_{{ manglePkgName pkg.name }}(major1,major2,minor) (\
  (major1) <  {{ pkg.x }} || \
  (major1) == {{ pkg.x }} && (major2) <  {{ pkg.y }} || \
  (major1) == {{ pkg.x }} && (major2) == {{ pkg.y }} && (minor) <= {{ pkg.z }})
#endif /* MIN_VERSION_{{ manglePkgName pkg.name }} */
{% endfor %}

{% for tool in tools %}
/* package {{ tool.name }}-{{ tool.version }} */
#ifndef TOOL_VERSION_{{ mangleStr tool.name }}
#define TOOL_VERSION_{{ mangleStr tool.name }} "{{ tool.version }}"
#endif /* VERSION_{{ mangleStr tool.name }} */
#ifndef MIN_TOOL_VERSION_{{ mangleStr tool.name }}
#define MIN_TOOL_VERSION_{{ mangleStr tool.name }}(major1,major2,minor) (\
  (major1) <  {{ tool.x }} || \
  (major1) == {{ tool.x }} && (major2) <  {{ tool.y }} || \
  (major1) == {{ tool.x }} && (major2) == {{ tool.y }} && (minor) <= {{ tool.z }})
#endif /* MIN_VERSION_{{ mangleStr tool.name }} */
{% endfor %}

{% if notNull packageKey %}
#ifndef CURRENT_packageKey
#define CURRENT_packageKey "{{ packageKey }}"
#endif /* CURRENT_packageKey */
{% endif %}
{% if notNull componentId %}
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "{{ componentId }}"
#endif /* CURRENT_COMPONENT_ID */
{% endif  %}
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "{{ packageVersion }}"
#endif /* CURRENT_PACKAGE_VERSION */
