cabal-version:      2.4
name:               mypkg
version:            0.1
synopsis:           Package with a main library and an internal library
license:            BSD-3-Clause
build-type:         Simple

library
  hs-source-dirs:   src
  exposed-modules:  MyPkg
  build-depends:    base
  default-language: Haskell2010

library inner
  hs-source-dirs:   inner-src
  exposed-modules:  MyPkg.Inner
  build-depends:    base
  default-language: Haskell2010
