Cabal-Version:      3.8

Name:               cabal-install
Version:            3.19.0.0
Synopsis:           The command-line interface for Cabal and Hackage.
Description:
    The \'cabal\' command-line program simplifies the process of managing
    Haskell software by automating the fetching, configuration, compilation
    and installation of Haskell libraries and programs.
homepage:           http://www.haskell.org/cabal/
bug-reports:        https://github.com/haskell/cabal/issues
License:            BSD-3-Clause
License-File:       LICENSE
Author:             Cabal Development Team (see AUTHORS file)
Maintainer:         Cabal Development Team <cabal-devel@haskell.org>
Copyright:          2003-2026, Cabal Development Team
Category:           Distribution
Build-type:         Simple
Extra-Source-Files:
  bash-completion/cabal
extra-doc-files:
  README.md
  ChangeLog.md

source-repository head
  type:     git
  location: https://github.com/haskell/cabal/
  subdir:   cabal-install

flag git-rev
  description: include Git revision hash in version
  default: False
  manual: True

common warnings
    ghc-options:
      -Wall
      -Wcompat
      -Wnoncanonical-monad-instances
      -Wincomplete-uni-patterns
      -Wincomplete-record-updates
      -Wno-unticked-promoted-constructors

    if impl(ghc < 8.8)
      ghc-options: -Wnoncanonical-monadfail-instances

    if impl(ghc >= 9.14)
      ghc-options: -Wno-pattern-namespace-specifier -Wno-incomplete-record-selectors

common base-dep
    build-depends:
      , base >=4.17 && <4.24

common cabal-dep
    build-depends:
      , Cabal ^>=3.19

common cabal-syntax-dep
    build-depends:
      , Cabal-syntax ^>=3.19

common cabal-install-solver-dep
    build-depends:
      , cabal-install-solver ^>=3.19

common cabal-install-internal-dep
    build-depends:
      , cabal-install-internal ^>=3.19

library
    import: warnings, base-dep, cabal-dep, cabal-syntax-dep, cabal-install-internal-dep
    default-language: GHC2021
    -- Disabling ImportQualifiedPost, otherwise fourmolu jumps ahead to apply it everywhere
    default-extensions: TypeOperators
                        NoImportQualifiedPost
                        PatternSynonyms
                        LambdaCase
                        BlockArguments

    hs-source-dirs:   src
    autogen-modules:
        Paths_cabal_install
    other-modules:
        Paths_cabal_install

    exposed-modules:
        Distribution.Client.API.Build
        Distribution.Client.API.Config
        Distribution.Client.API.PackageIndex
        Distribution.Client.API.Project

    build-depends:
      , containers  >= 0.5.6.2 && < 0.9
      , filepath    >= 1.4.0.0 && < 1.6

executable cabal
    import: warnings, base-dep, cabal-install-internal-dep
    main-is: Main.hs
    hs-source-dirs: main
    default-language: GHC2021
    -- Disabling ImportQualifiedPost, otherwise fourmolu jumps ahead to apply it everywhere
    default-extensions: NoImportQualifiedPost

    ghc-options: -rtsopts -threaded

    -- On AIX, some legacy BSD operations such as flock(2) are provided by libbsd.a
    if os(aix)
        extra-libraries: bsd

    if flag(git-rev)
      cpp-options: -DGIT_REV

-- Small, fast running tests.
--
test-suite unit-tests
    import: warnings, base-dep, cabal-dep, cabal-syntax-dep, cabal-install-solver-dep, cabal-install-internal-dep
    default-language: GHC2021
    -- Disabling ImportQualifiedPost, otherwise fourmolu jumps ahead to apply it everywhere
    default-extensions: TypeOperators
                        NoImportQualifiedPost
    ghc-options: -rtsopts -threaded

    type: exitcode-stdio-1.0
    main-is: UnitTests.hs
    hs-source-dirs: tests
    other-modules:
      UnitTests.Distribution.Client.ArbitraryInstances
      UnitTests.Distribution.Client.BuildReport
      UnitTests.Distribution.Client.Configure
      UnitTests.Distribution.Client.FetchUtils
      UnitTests.Distribution.Client.Get
      UnitTests.Distribution.Client.Glob
      UnitTests.Distribution.Client.HttpUtils
      UnitTests.Distribution.Client.GZipUtils
      UnitTests.Distribution.Client.IndexUtils
      UnitTests.Distribution.Client.IndexUtils.ActiveRepos
      UnitTests.Distribution.Client.IndexUtils.Timestamp
      UnitTests.Distribution.Client.Init
      UnitTests.Distribution.Client.Init.Golden
      UnitTests.Distribution.Client.Init.Interactive
      UnitTests.Distribution.Client.Init.NonInteractive
      UnitTests.Distribution.Client.Init.Simple
      UnitTests.Distribution.Client.Init.Utils
      UnitTests.Distribution.Client.Init.FileCreators
      UnitTests.Distribution.Client.InstallPlan
      UnitTests.Distribution.Client.JobControl
      UnitTests.Distribution.Client.ProjectConfig
      UnitTests.Distribution.Client.ProjectPlanning
      UnitTests.Distribution.Client.Store
      UnitTests.Distribution.Client.Tar
      UnitTests.Distribution.Client.Targets
      UnitTests.Distribution.Client.TreeDiffInstances
      UnitTests.Distribution.Client.UserConfig
      UnitTests.Distribution.Solver.Modular.Builder
      UnitTests.Distribution.Solver.Modular.RetryLog
      UnitTests.Distribution.Solver.Modular.Solver
      UnitTests.Distribution.Solver.Modular.DSL
      UnitTests.Distribution.Solver.Modular.DSL.TestCaseUtils
      UnitTests.Distribution.Solver.Modular.WeightedPSQ
      UnitTests.Distribution.Solver.Types.OptionalStanza
      UnitTests.Options

    build-depends:
      , array
      , bytestring
      , Cabal-tree-diff
      , Cabal-QuickCheck
      , Cabal-tests
      , containers
      , directory
      , filepath
      , mtl
      , network-uri >= 2.6.2.0 && <2.7
      , random
      , tar
      , time
      , zlib
      , tasty >= 1.2.3 && <1.6
      , tasty-golden >=2.3.1.1 && <2.4
      , tasty-quickcheck ^>=0.11
      , tasty-expected-failure
      , tasty-hunit >= 0.10
      , tree-diff
      , QuickCheck >= 2.14.3 && <2.19

-- Tests for the project file parser
test-suite parser-tests
    import: warnings, base-dep, cabal-dep, cabal-syntax-dep, cabal-install-solver-dep, cabal-install-internal-dep
    default-language: GHC2021
    -- Disabling ImportQualifiedPost, otherwise fourmolu jumps ahead to apply it everywhere
    default-extensions: NoImportQualifiedPost
    ghc-options: -rtsopts -threaded

    type: exitcode-stdio-1.0
    main-is: Tests.hs
    hs-source-dirs: parser-tests
    build-depends:
      , containers
      , directory
      , filepath
      , network-uri >= 2.6.2.0 && <2.7
      , tasty >= 1.2.3 && <1.6
      , tasty-hunit >= 0.10
    other-modules:
      Tests.ParserTests

-- Tests to run with a limited stack and heap size
-- The test suite name must be keep short cause a longer one
-- could make the build generating paths which exceeds the windows
-- max path limit (still a problem for some ghc versions)
test-suite mem-use-tests
  import: warnings, base-dep, cabal-dep, cabal-syntax-dep, cabal-install-solver-dep, cabal-install-internal-dep
  type: exitcode-stdio-1.0
  main-is: MemoryUsageTests.hs
  hs-source-dirs: tests
  default-language: GHC2021
  -- Disabling ImportQualifiedPost, otherwise fourmolu jumps ahead to apply it everywhere
  default-extensions: NoImportQualifiedPost

  ghc-options: -threaded -rtsopts "-with-rtsopts=-M16M -K1K"

  other-modules:
    UnitTests.Distribution.Solver.Modular.DSL
    UnitTests.Distribution.Solver.Modular.DSL.TestCaseUtils
    UnitTests.Distribution.Solver.Modular.MemoryUsage
    UnitTests.Options

  build-depends:
    , containers
    , tasty >= 1.2.3 && <1.6
    , tasty-hunit >= 0.10


-- Integration tests that use the cabal-install code directly
-- but still build whole projects
test-suite integration-tests2
  import: warnings, base-dep, cabal-dep, cabal-syntax-dep, cabal-install-solver-dep, cabal-install-internal-dep
  ghc-options: -rtsopts -threaded
  type: exitcode-stdio-1.0
  main-is: IntegrationTests2.hs
  hs-source-dirs: tests
  default-language: GHC2021
  -- Disabling ImportQualifiedPost, otherwise fourmolu jumps ahead to apply it everywhere
  default-extensions: NoImportQualifiedPost

  build-depends:
    , bytestring
    , containers
    , directory
    , filepath
    , process
    , tasty >= 1.5.4 && <1.6
    , tasty-hunit >= 0.10
    , tasty-expected-failure
    , silently
    , tagged

test-suite long-tests
  import: warnings, base-dep, cabal-dep, cabal-syntax-dep, cabal-install-solver-dep, cabal-install-internal-dep
  ghc-options: -rtsopts -threaded
  type: exitcode-stdio-1.0
  hs-source-dirs: tests
  main-is: LongTests.hs
  default-language: GHC2021
  -- Disabling ImportQualifiedPost, otherwise fourmolu jumps ahead to apply it everywhere
  default-extensions: NoImportQualifiedPost

  other-modules:
    UnitTests.Distribution.Client.ArbitraryInstances
    UnitTests.Distribution.Client.Described
    UnitTests.Distribution.Client.DescribedInstances
    UnitTests.Distribution.Client.FileMonitor
    UnitTests.Distribution.Client.VCS
    UnitTests.Distribution.Solver.Modular.DSL
    UnitTests.Distribution.Solver.Modular.QuickCheck
    UnitTests.Distribution.Solver.Modular.QuickCheck.Utils
    UnitTests.Options

  build-depends:
    , Cabal-QuickCheck
    , Cabal-described
    , Cabal-tests
    , containers
    , directory
    , filepath
    , mtl
    , network-uri >= 2.6.2.0 && <2.7
    , random
    , tagged
    , tasty >= 1.2.3 && <1.6
    , tasty-expected-failure
    , tasty-hunit >= 0.10
    , tasty-quickcheck <0.12
    , QuickCheck >= 2.14 && <2.19
    , pretty-show >= 1.6.15
