{-# LANGUAGE ForeignFunctionInterface, CApiFFI #-}

module A ( bobble, isNeeded ) where

import Foreign.C.Types ( CInt(..) )

-- B is autogenerated
import B ( foo, isNeeded )

bar x = 2 + foo x * 3

foreign export ccall bar :: CInt -> CInt

wobble x = gen_quux x

foreign import capi "Gen.h gen_quux" gen_quux :: CInt -> CInt
foreign import capi "Gen.h gen_nozzle" gen_nozzle :: CInt -> CInt

foreign import capi "Top.h wyzzy" wyzzy :: CInt -> CInt

bobble = wyzzy 0

foreign export ccall wobble :: CInt -> CInt
