module Main where

-- bt
import Tool
  ( mkTool )
import Paths_bt -- (Cabal autogenerated module)
  ( getDataFileName )

--------------------------------------------------------------------------------

main :: IO ()
main = do
  customDataFile <- getDataFileName "PP1.txt"
  mkTool "custom-pp1" customDataFile
