-- Tests whether an extra C source can depend on a _stub header generated by
-- GHC compiling a Haskell module with a foreign export declaration

import Test.Cabal.Prelude
main = cabalTest $ do
    cabal "v2-build" []
