#!/usr/bin/env bash

declare -A args

for x in "${@}"; do
    if [[ "$x" =~ ^"@" ]]; then
       while IFS= read -d $'\n' -r arg ; do
           x="$arg"
           if [[ -v args["$x"] ]]; then
               echo "Duplicate argument detected: '$x'"
               echo "All args: $(cat "${x#@}")"
               echo "Duplicate argument detected: '$x'" >&2
               echo "All args: $(cat "${x#@}")" >&2
               exit 1
           fi
           args["$x"]=1
       done <"${x#@}"
    fi

    if [[ -v args["$x"] ]]; then
        echo "Duplicate argument detected: '$x'"
        echo "All args: ${@}"
        echo "Duplicate argument detected: '$x'. All args: ${@}" >&2
        echo "All args: ${@}" >&2
        exit 1
    fi
    args["$x"]=1
done

if which cc >/dev/null 2>&1; then
    cc -DNOERROR6 "${@}"
elif which gcc >/dev/null 2>&1; then
    gcc -DNOERROR6 "${@}"
elif which clang >/dev/null 2>&1; then
    clang -DNOERROR6 "${@}"
else
    echo "Cannot find C compiler" >&2
    exit 1
fi
