name: fourmolu
on: push
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # Note that you must checkout your code before running haskell-actions/run-fourmolu
      - uses: actions/checkout@v2
      - uses: haskell-actions/run-fourmolu@v9
        with:
          version: "0.12.0.0"