name: Linting

on:
  pull_request:
  push:

jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: haskell-actions/hlint-setup@v2
      with:
        version: "3.10"
    - uses: haskell-actions/hlint-run@v2
      with:
        path: "."
        fail-on: suggestion
