name: Linting

on:
  pull_request:
  push:
    branches: ["master"]

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/run-fourmolu@v8
      with:
        pattern: |
          Cabal/**/*.hs
          Cabal-syntax/**/*.hs
          Cabal-install/**/*.hs
          Cabal-QuickCheck/**/*.hs
          Cabal-described/**/*.hs
          Cabal-tests/**/*.hs
          Cabal-tree-diff/**/*.hs
          cabal-benchmarks/**/*.hs
          cabal-dev-scripts/**/*.hs
          cabal-install-solver/**/*.hs
          solver-benchmarks/**/*.hs
          !Cabal-syntax/src/Distribution/Fields/Lexer.hs
          !Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs
          !Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
          !Cabal/src/Distribution/Simple/Build/Macros/Z.hs
          !Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
          !cabal-testsuite
