name: Linux

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  validate:
    name: Validate ${{ matrix.ghc }}

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        include:
          - ghc: "9.2.1"
            flags: ""
            cli: true
            experimental: true
          - ghc: "9.0.2"
            flags: ""
            cli: true
          - ghc: "8.10.7"
            flags: ""
            cli: true
          - ghc: "8.8.4"
            flags: "--solver-benchmarks"
            cli: true
          - ghc: "8.6.5"
            flags: "--complete-hackage-tests"
            cli: true
          - ghc: "8.4.4"
            flags: ""
            cli: true
          - ghc: "8.2.2"
            flags: ""
            cli: true
          - ghc: "8.0.2"
            flags: "--lib-only"
            cli: false

    steps:

      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest # default, keeping for visibility

      #  See the following link for a breakdown of the following step
      #  https://github.com/haskell/actions/issues/7#issuecomment-745697160
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Validate print-config
        run: sh validate.sh -j 2 -w ghc-${{ matrix.ghc }} -v ${{ matrix.flags }} -s print-config

      - name: Validate print-tool-versions
        run: sh validate.sh -j 2 -w ghc-${{ matrix.ghc }} -v ${{ matrix.flags }} -s print-tool-versions

      - name: Validate build
        run: sh validate.sh -j 2 -w ghc-${{ matrix.ghc }} -v ${{ matrix.flags }} -s build

      - name: Validate lib-tests
        run: sh validate.sh -j 2 -w ghc-${{ matrix.ghc }} -v ${{ matrix.flags }} -s lib-tests

      - name: Validate lib-suite
        run: sh validate.sh -j 2 -w ghc-${{ matrix.ghc }} -v ${{ matrix.flags }} -s lib-suite

      - name: Validate cli-tests
        if: matrix.cli == true
        run: sh validate.sh -j 2 -w ghc-${{ matrix.ghc }} -v ${{ matrix.flags }} -s cli-tests

      - name: Validate cli-suite
        if: matrix.cli == true
        run: sh validate.sh -j 2 -w ghc-${{ matrix.ghc }} -v ${{ matrix.flags }} -s cli-suite

