name: Matrix Notification

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  notify-matrix:
    if: "github.event.label.name == 'priority: high :fire:'"
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification to Matrix
        uses: Cadair/matrix-notify-action@main
        with:
          # token for @cabal-notification-bot:matrix.org (owned by Artem)
          token: ${{ secrets.MATRIX_TOKEN }}
          homeserver: 'https://matrix.org'
          # roomid for #hcakage:matrix.org
          roomid: '!YWYQDCuIpuQHzGrLzd:matrix.org'
          message: |
            @${{ github.actor }} marked as a high priority item:

            * [${{ github.event.issue.title || github.event.pull_request.title }}](${{ github.event.issue.html_url || github.event.pull_request.html_url }})
