name: Windows

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  test-windows:
    strategy:
      matrix:
        ghc:
          - "8.6.5"
          - "8.10.4"

    name: test ghc-${{ matrix.ghc }}
    runs-on: windows-latest
    steps:
      - uses: actions/setup-haskell@v1.1.4
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.4.0.0'
      - name: Print versions
        run: |
          [Environment]::GetEnvironmentVariable("Path")
          cabal --version
          ghc --version
          cabal user-config init -a "http-transport: plain-http" -a "store-dir: C:\SR" -f -v3
      - uses: actions/cache@v1
        with:
          path: C:\SR
          key: windows-store-meta
      - uses: actions/checkout@v2
      # all dependencies of Cabal already there (due to GHC depending on Cabal)
      - name: cabal v2-build Cabal
        run: cabal v2-build Cabal
      # We cannot ask for all dependencies, but we can for cabal-install.
      - name: cabal v2-build cabal-install --only-dependencies
        run: cabal v2-build cabal-install --only-dependencies
      - name: cabal v2-build
        run: cabal v2-build all
      - name: Cabal unit-tests
        run: |
          cabal v2-test Cabal-tests
      - name: cabal-install memory-usage-tests
        run: |
          cd cabal-install
          cabal v2-run cabal-install:memory-usage-tests
      - name: cabal-install long-tests
        run: |
          cd cabal-install
          cabal v2-run cabal-install:long-tests -- --pattern "! (/FileMonitor/ || /VCS/ || /Get/)"
      - name: cabal-install integration-tests2
        run: |
          cd cabal-install
          cabal v2-run cabal-install:integration-tests2
      - name: cabal-install unit-tests
        run: |
          cd cabal-install
          cabal v2-run cabal-install:unit-tests -- --pattern "! (/FileMonitor/ || /VCS/ || /Get/)"
      - name: cabal-tests
        # Using only one job, -j1, to fail less.
        run: cabal v2-run cabal-testsuite:cabal-tests -- -j1 --with-cabal=dist-newstyle\build\x86_64-windows\ghc-${{ matrix.ghc }}\cabal-install-3.7.0.0\x\cabal\build\cabal\cabal.exe

  # TODO: store the exe from above as artifact and re-use it here instead of building anew
  test-windows-dogfood:
    strategy:
      matrix:
        ghc:
          - "8.6.5"
          - "8.10.4"
    name: test ghc-${{ matrix.ghc }} dogfood
    runs-on: windows-latest
    steps:
      - uses: actions/setup-haskell@v1.1.4
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.4.0.0'
      - name: Print versions
        run: |
          [Environment]::GetEnvironmentVariable("Path")
          cabal --version
          ghc --version
          cabal user-config init -a "http-transport: plain-http" -a "store-dir: C:\SR" -f -v3
      - uses: actions/cache@v1
        with:
          path: C:\SR
          key: windows-store-meta
      - name: Update Hackage index
        run: cabal v2-update
      - uses: actions/checkout@v2
      # all dependencies of Cabal already there (due to GHC depending on Cabal)
      - name: cabal v2-build Cabal
        run: cabal v2-build Cabal
      # We cannot ask for all dependencies, but we can for cabal-install.
      - name: cabal v2-build cabal-install --only-dependencies
        run: cabal v2-build cabal-install --only-dependencies
      - name: cabal v2-build
        run: cabal v2-build all
      - name: wipe out cabal store
        run: Remove-Item -Recurse -Force C:\SR
      - name: eat its own dogfood by building own Cabal source with itself
        run: |
          cp $(cabal list-bin exe:cabal) ./cabal-exe-current
          ./cabal-exe-current --version
          ./cabal-exe-current v2-build Cabal
        shell: bash
      - name: eat its own dogfood by building all deps with itself
        run: ./cabal-exe-current v2-build cabal-install --only-dependencies
        shell: bash
      - name: eat its own dogfood by building own source with itself
        run: ./cabal-exe-current v2-build all
        shell: bash
